package com.example.cpsc411petownerapp.database.UserData

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Create a data class for User
 */
@Entity(tableName = "user_table")
data class User(

    // Defines the table's primary key. Primary keys are unique values that can be autogenerated.
    // They are used to differentiate one entity from another.
    @PrimaryKey(autoGenerate = true)
    var userId: Long = 0L,

    // Non-primary key columns. Data type is specified in the property.
    @ColumnInfo()
    var username: String = "",

    @ColumnInfo()
    var password: String = "",

    @ColumnInfo()
    var email: String = ""
)